try to fix RPC check

diff --git a/.github/workflows/deploy-program.yml b/.github/workflows/deploy-program.yml
--- a/.github/workflows/deploy-program.yml
+++ b/.github/workflows/deploy-program.yml
@@ -79,8 +79,11 @@ jobs:
         run: |
           if [ "${{ inputs.cluster }}" == "devnet" ]; then
             echo RPC=${{ secrets.DEVNET_RPC }} >> $GITHUB_ENV
-          else
+          else if [ "${{ inputs.cluster }}" == "mainnet" ]; then
             echo RPC=${{ secrets.MAINNET_RPC }} >> $GITHUB_ENV
+          else
+            echo "Invalid cluster"
+            exit 1
           fi
 
       - name: Identify Program
@@ -102,7 +105,7 @@ jobs:
           echo ${{ env.PROGRAM_ID }} > ./program-id.json
 
           solana config set -k ./deploy-key.json
-          solana config set --url ${{ env.RPC }}
+          solana config set --url ${{ secrets.RPC }}
 
           buffer=$(solana program write-buffer ./program-builds/programs/${{ inputs.program }}/target/deploy/${{ env.PROGRAM_NAME }}.so | awk '{print $2}')
           solana program set-buffer-authority --new-buffer-authority ERYcfk9iB7XBFPYfxwEVbFGj3WyyqZs4DjCdo77p5uNc $buffer
